// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2026_peminjaman_ruangan_backend.Data;

#nullable disable

namespace _2026_peminjaman_ruangan_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209022307_UpdatePeminjamanModel")]
    partial class UpdatePeminjamanModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_2026_peminjaman_ruangan_backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Peminjam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Peminjamans");
                });

            modelBuilder.Entity("_2026_peminjaman_ruangan_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            IsAvailable = true,
                            Location = "Gedung D3",
                            Name = "Ruang Teori 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            IsAvailable = true,
                            Location = "Gedung D4",
                            Name = "Lab Informatika"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            IsAvailable = true,
                            Location = "Gedung TC",
                            Name = "Aula Pens"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            IsAvailable = false,
                            Location = "Gedung Pusat",
                            Name = "Ruang Rapat"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 50,
                            IsAvailable = true,
                            Location = "Gedung Pasca",
                            Name = "Theater PENS"
                        });
                });

            modelBuilder.Entity("_2026_peminjaman_ruangan_backend.Models.Peminjaman", b =>
                {
                    b.HasOne("_2026_peminjaman_ruangan_backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
